In [52]:
import pandas as pd
data={'rollno':[101,102,103,104,105,106,107,108,109,110],
'name':['arun','priya','rahul','pooja','vaish','rishi','harni','pushpa','mathi','suba'],
'marks':[80,90,70,85,95,75,65,55,97,87]}
df=pd.DataFrame(data)
print(df)

   rollno    name  marks
0     101    arun     80
1     102   priya     90
2     103   rahul     70
3     104   pooja     85
4     105   vaish     95
5     106   rishi     75
6     107   harni     65
7     108  pushpa     55
8     109   mathi     97
9     110    suba     87

In [54]:
print(df.columns)

Index(['rollno', 'name', 'marks'], dtype='object')

In [55]:
print(df.size)

30

In [56]:
print(df.shape)

(10, 3)

In [57]:
print(df.index)

RangeIndex(start=0, stop=10, step=1)

In [58]:
print(df.dtypes)

rollno     int64
name      object
marks      int64
dtype: object

In [59]:
print(df['name'])

0      arun
1     priya
2     rahul
3     pooja
4     vaish
5     rishi
6     harni
7    pushpa
8     mathi
9      suba
Name: name, dtype: object

In [60]:
print(df[['name','marks']])

     name  marks
0    arun     80
1   priya     90
2   rahul     70
3   pooja     85
4   vaish     95
5   rishi     75
6   harni     65
7  pushpa     55
8   mathi     97
9    suba     87

In [62]:
print(df.loc[0])

rollno     101
name      arun
marks       80
Name: 0, dtype: object

In [63]:
print(df.loc[[0,1]])

   rollno   name  marks
0     101   arun     80
1     102  priya     90

In [64]:
print(df.iloc[1])

rollno      102
name      priya
marks        90
Name: 1, dtype: object

In [65]:
print(df.iloc[['1','2']])

   rollno   name  marks
1     102  priya     90
2     103  rahul     70

In [66]:
print(df.iloc[0:2,1:3])

    name  marks
0   arun     80
1  priya     90

In [68]:
df['marks']=df['marks']+5
print(df)

   rollno    name  marks
0     101    arun     85
1     102   priya     95
2     103   rahul     75
3     104   pooja     90
4     105   vaish    100
5     106   rishi     80
6     107   harni     70
7     108  pushpa     60
8     109   mathi    102
9     110    suba     92

In [71]:
print(df['marks'].sum())

849

In [72]:
print(df['marks'].mean())

84.9

In [73]:
print(df['marks'].max())

102

In [74]:
print(df['marks'].min())

60

In [75]:
df.sort_values('marks',ascending=False)

   rollno    name  marks
8     109   mathi    102
4     105   vaish    100
1     102   priya     95
9     110    suba     92
3     104   pooja     90
0     101    arun     85
5     106   rishi     80
2     103   rahul     75
6     107   harni     70
7     108  pushpa     60

In [76]:
df.sort_values('marks',ascending=True)

   rollno    name  marks
7     108  pushpa     60
6     107   harni     70
2     103   rahul     75
5     106   rishi     80
0     101    arun     85
3     104   pooja     90
9     110    suba     92
1     102   priya     95
4     105   vaish    100
8     109   mathi    102

In [77]:
print(df[df['marks']>80])

   rollno   name  marks
0     101   arun     85
1     102  priya     95
3     104  pooja     90
4     105  vaish    100
8     109  mathi    102
9     110   suba     92

In [78]:
print(df[df['marks']<90])

   rollno    name  marks
0     101    arun     85
2     103   rahul     75
5     106   rishi     80
6     107   harni     70
7     108  pushpa     60

In [79]:
df.head()

   rollno   name  marks
0     101   arun     85
1     102  priya     95
2     103  rahul     75
3     104  pooja     90
4     105  vaish    100

In [80]:
df.tail()

   rollno    name  marks
5     106   rishi     80
6     107   harni     70
7     108  pushpa     60
8     109   mathi    102
9     110    suba     92

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rollno  10 non-null     int64
 1   name    10 non-null     object
 2   marks   10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [82]:
df.describe()

          rollno      marks
count   10.00000   10.00000
mean   105.50000   84.90000
std      3.02765   13.59289
min    101.00000   60.00000
25%    103.25000   76.25000
50%    105.50000   87.50000
75%    107.75000   94.25000
max    110.00000  102.00000

In [85]:
import pandas as pd
data={'rollno':[101,102,103,104,105,106,107,108,109,110],
'name':['arun','priya','rahul','pooja','vaish','rishi','harni','pushpa','mathi','suba'],
'dept':['cs','ai','viscom','bba','bca','bcom','mca','it','english','tamil'],
'marks':[95,85,75,65,55,67,78,89,92,57],
'cgpa':[9,8,7,6,5,6,7,8,9,5]}
df=pd.DataFrame(data)
print(df)

   rollno    name     dept  marks  cgpa
0     101    arun       cs     95     9
1     102   priya       ai     85     8
2     103   rahul   viscom     75     7
3     104   pooja      bba     65     6
4     105   vaish      bca     55     5
5     106   rishi     bcom     67     6
6     107   harni      mca     78     7
7     108  pushpa       it     89     8
8     109   mathi  english     92     9
9     110    suba    tamil     57     5

In [86]:
print(df['marks'].sum())

758

In [87]:
print(df['marks'].mean())

75.8

In [88]:
print(df['marks'].max())

95

In [89]:
print(df['marks'].min())

55

In [90]:
import pandas as pd
data={'employee':['pooja','rishi','vaish','priya'],
      'salary':[50000,40000,45000,35000]}
df=pd.DataFrame(data)
print(df)

  employee  salary
0    pooja   50000
1    rishi   40000
2    vaish   45000
3    priya   35000

In [91]:
print(df[df['salary']>40000])

  employee  salary
0    pooja   50000
2    vaish   45000

In [92]:
df.sort_values('salary',ascending=True)

  employee  salary
3    priya   35000
1    rishi   40000
2    vaish   45000
0    pooja   50000

In [94]:
df.sort_values('salary',ascending=False)

  employee  salary
0    pooja   50000
2    vaish   45000
1    rishi   40000
3    priya   35000