In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("C:/Users/Ibscai22/hepatitis.csv")
df.head()

,sepal_len,sepal_wid,petal_len,petal_wid,cls
0,"2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1",NaN,NaN,NaN,NaN
1,"2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1",NaN,NaN,NaN,NaN
2,"2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1",NaN,NaN,NaN,NaN
3,"2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1",NaN,NaN,NaN,NaN
4,"2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1",NaN,NaN,NaN,NaN

In [6]:
df.isnull()

     sepal_len  sepal_wid  petal_len  petal_wid   cls
0        False       True       True       True  True
1        False       True       True       True  True
2        False       True       True       True  True
3        False       True       True       True  True
4        False       True       True       True  True
..         ...        ...        ...        ...   ...
149      False       True       True       True  True
150      False       True       True       True  True
151      False       True       True       True  True
152      False       True       True       True  True
153      False       True       True       True  True

[154 rows x 5 columns]

In [7]:
df.isnull().sum()

sepal_len      0
sepal_wid    154
petal_len    154
petal_wid    154
cls          154
dtype: int64

In [10]:
df['sepal_wid']=df['sepal_wid'].fillna(7)

In [11]:
df.isnull().sum()

sepal_len      0
sepal_wid      0
petal_len    154
petal_wid    154
cls          154
dtype: int64

In [12]:
mn=df['petal_len'].mean()
mn

nan

In [15]:
df['petal_len']=df['petal_len'].fillna(mn)

In [16]:
df.isnull().sum()

sepal_len      0
sepal_wid      0
petal_len    154
petal_wid    154
cls          154
dtype: int64

In [17]:
med=df['petal_wid'].median()
med

nan

In [18]:
df['petal_wid']=df['petal_wid'].fillna(med)

In [19]:
df.isnull().sum()

sepal_len      0
sepal_wid      0
petal_len    154
petal_wid    154
cls          154
dtype: int64

In [21]:
mod=df['petal_wid'].mode()
mod

Series([], Name: petal_wid, dtype: float64)

In [22]:
df['petal_wid']=df['petal_wid'].fillna(mod)

In [23]:
df.isnull().sum()

sepal_len      0
sepal_wid      0
petal_len    154
petal_wid    154
cls          154
dtype: int64

In [24]:
df['petal_wid']=df['petal_wid'].ffill()
df.isnull().sum()

sepal_len      0
sepal_wid      0
petal_len    154
petal_wid    154
cls          154
dtype: int64

In [25]:
df['cls']=df['cls'].bfill()
df.isnull().sum()

sepal_len      0
sepal_wid      0
petal_len    154
petal_wid    154
cls          154
dtype: int64