In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Ibscai22.DGVC-MCA\students.csv")
print(df)

   rollno   name department  marks
0     101   arun        cse     95
1     102  priya         ai     92
2     103  rahul         it     78
3     104  divya        cse     88

In [5]:
df.head(2)

   rollno   name department  marks
0     101   arun        cse     95
1     102  priya         ai     92

In [6]:
df.tail(2)

   rollno   name department  marks
2     103  rahul         it     78
3     104  divya        cse     88

In [7]:
print(df.loc[1])

rollno          102
name          priya
department       ai
marks            92
Name: 1, dtype: object

In [8]:
print(df.loc[2])

rollno          103
name          rahul
department       it
marks            78
Name: 2, dtype: object

In [10]:
print(df[df['marks']>80])

   rollno   name department  marks
0     101   arun        cse     95
1     102  priya         ai     92
3     104  divya        cse     88

In [13]:
df['grade']=['A+','A','C','B']
print(df)

   rollno   name department  marks grade
0     101   arun        cse     95    A+
1     102  priya         ai     92     A
2     103  rahul         it     78     C
3     104  divya        cse     88     B

In [15]:
df['marks']=df['marks']+5
print(df)

   rollno   name department  marks grade
0     101   arun        cse    105    A+
1     102  priya         ai    102     A
2     103  rahul         it     88     C
3     104  divya        cse     98     B